export const OPERATIVES = [
  {
    id: 'socrates',
    name: 'Sócrates',
    mark: 'S',
    role: 'RANGED / COMBAT MEDIC',
    maxHealth: 118,
    moveSpeed: 9.4,
    color: 0x58d2c7,
    attack: {
      kind: 'projectile',
      cooldown: 0.27,
      damage: 25,
      projectileSpeed: 25,
      range: 24,
      pierce: 0,
    },
    ability: {
      id: 'field-clinic',
      name: 'FIELD CLINIC',
      cooldown: 13,
      description: 'Heals the squad and weakens nearby hostile processes.',
    },
    dodge: { cooldown: 1.15, distance: 5.2 },
    fieldTrait: 'Every third projectile hit restores 3 health.',
  },
  {
    id: 'zelia-amato',
    name: 'Zélia Amato',
    mark: 'Z',
    role: 'MELEE / BREACHER',
    maxHealth: 165,
    moveSpeed: 8.3,
    color: 0xe0b660,
    attack: {
      kind: 'melee',
      cooldown: 0.58,
      damage: 49,
      radius: 3.35,
      knockback: 8.2,
    },
    ability: {
      id: 'kiln-breaker',
      name: 'KILN BREAKER',
      cooldown: 11,
      description: 'A heavy radial fracture that launches and stuns enemies.',
    },
    dodge: { cooldown: 1.35, distance: 4.5 },
    fieldTrait: 'Melee eliminations grant temporary damage resistance.',
  },
  {
    id: 'lia',
    name: 'Lia',
    mark: 'L',
    role: 'RANGED / ROUTE CONTROLLER',
    maxHealth: 105,
    moveSpeed: 10.1,
    color: 0x7ea8ff,
    attack: {
      kind: 'projectile',
      cooldown: 0.36,
      damage: 19,
      projectileSpeed: 29,
      range: 27,
      pierce: 1,
    },
    ability: {
      id: 'route-fold',
      name: 'ROUTE FOLD',
      cooldown: 9,
      description: 'Folds distance, relocating Lia and cutting everything on the route.',
    },
    dodge: { cooldown: 0.9, distance: 5.8 },
    fieldTrait: 'Projectiles pierce one hostile and gain damage after doing so.',
  },
  {
    id: 'kindred',
    name: 'Kindred',
    mark: 'K',
    role: 'MELEE / NIGHT SKIRMISHER',
    maxHealth: 132,
    moveSpeed: 10.5,
    color: 0xd68bd2,
    attack: {
      kind: 'melee',
      cooldown: 0.38,
      damage: 31,
      radius: 2.65,
      knockback: 4.8,
    },
    ability: {
      id: 'night-passage',
      name: 'NIGHT PASSAGE',
      cooldown: 10,
      description: 'Phases through a short route and tears at enemies on exit.',
    },
    dodge: { cooldown: 0.78, distance: 6.1 },
    fieldTrait: 'Close-range eliminations restore a small amount of health.',
  },
];

export function operativeById(id) {
  return OPERATIVES.find((operative) => operative.id === id) ?? OPERATIVES[0];
}
