export const COMBAT_KITS = [
  {
    id: 'field-medic',
    behaviorId: 'socrates',
    name: 'FIELD MEDIC',
    family: 'ranged',
    role: 'RANGED / COMBAT MEDIC',
    maxHealth: 118,
    moveSpeed: 9.4,
    attack: {
      kind: 'projectile',
      cooldown: 0.27,
      damage: 25,
      projectileSpeed: 25,
      range: 24,
      pierce: 0,
    },
    ability: {
      id: 'field-clinic',
      name: 'FIELD CLINIC',
      cooldown: 13,
      description: 'Heals the team and weakens nearby hostile processes.',
    },
    dodge: { cooldown: 1.15, distance: 5.2 },
    fieldTrait: 'Every third projectile hit restores health.',
  },
  {
    id: 'breacher',
    behaviorId: 'zelia-amato',
    name: 'BREACHER',
    family: 'melee',
    role: 'MELEE / BREACHER',
    maxHealth: 165,
    moveSpeed: 8.3,
    attack: {
      kind: 'melee',
      cooldown: 0.58,
      damage: 49,
      radius: 3.35,
      knockback: 8.2,
    },
    ability: {
      id: 'kiln-breaker',
      name: 'KILN BREAKER',
      cooldown: 11,
      description: 'A heavy radial fracture that launches and stuns enemies.',
    },
    dodge: { cooldown: 1.35, distance: 4.5 },
    fieldTrait: 'Melee eliminations grant temporary damage resistance.',
  },
  {
    id: 'route-controller',
    behaviorId: 'lia',
    name: 'ROUTE CONTROLLER',
    family: 'ranged',
    role: 'RANGED / ROUTE CONTROLLER',
    maxHealth: 105,
    moveSpeed: 10.1,
    attack: {
      kind: 'projectile',
      cooldown: 0.36,
      damage: 19,
      projectileSpeed: 29,
      range: 27,
      pierce: 1,
    },
    ability: {
      id: 'route-fold',
      name: 'ROUTE FOLD',
      cooldown: 9,
      description: 'Folds distance, relocating the user and cutting everything on the route.',
    },
    dodge: { cooldown: 0.9, distance: 5.8 },
    fieldTrait: 'Projectiles pierce one hostile and gain damage after doing so.',
  },
  {
    id: 'night-skirmisher',
    behaviorId: 'kindred',
    name: 'NIGHT SKIRMISHER',
    family: 'melee',
    role: 'MELEE / NIGHT SKIRMISHER',
    maxHealth: 132,
    moveSpeed: 10.5,
    attack: {
      kind: 'melee',
      cooldown: 0.38,
      damage: 31,
      radius: 2.65,
      knockback: 4.8,
    },
    ability: {
      id: 'night-passage',
      name: 'NIGHT PASSAGE',
      cooldown: 10,
      description: 'Phases through a short route and tears at enemies on exit.',
    },
    dodge: { cooldown: 0.78, distance: 6.1 },
    fieldTrait: 'Close-range eliminations restore health.',
  },
];

export function combatKitById(id) {
  return COMBAT_KITS.find((kit) => kit.id === id) ?? COMBAT_KITS[0];
}
